apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-trek-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-trek
  template:
    metadata:
      labels:
        app: task-trek
    spec:
      containers:
        - name: task-trek-container
          image: ahmadmahmood96/task-trek:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
